name: Build Unity Android APK

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Free up space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc

      - name: Setup Unity
        uses: game-ci/unity-actions@v2
        with:
          version: 2019.4.40f1
          targetPlatform: Android

      - name: Build
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: Android

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Android-APK
          path: build/Android/*.apk
